name: Build dev extension from branch

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - id: cache-npm
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm ci
    
      - name: Build artifacts
        run: |
          npm run build:chrome

      - name: Remove key in manifest
        run: |
          sed -i '/"key":/d' extension/chrome/manifest.json
    
      - name: Store Chrome Development artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-dev
          path: |
            extension/chrome
