name: Build dev extension

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: "https://658b8e1fd3954c7fb6acc851dda97a4d@o512991.ingest.sentry.io/6223342"
      SENTRY_SAMPLE_RATE: 1.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Default to prod API
        run: |
          sed -r "s/DefaultBaseUrlKey = 'Dev'/DefaultBaseUrlKey = 'Prod'/" source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts

      - name: Set Sentry Settings
        run: |
          sed -r "s#\"SENTRY_DSN\": \"\",#\"SENTRY_DSN\": \"${SENTRY_DSN}\",#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json
          sed -r "s#\"SENTRY_SAMPLE_RATE\": 0.0,#\"SENTRY_SAMPLE_RATE\": ${SENTRY_SAMPLE_RATE},#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json
          cat source/witty.config.json
  
      - name: Install yarn
        run: |
          npm install --global yarn

      - id: cache-yarn
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Build artifacts
        run: |
          yarn run build:chrome

      - name: Store Chrome Development artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chrome-dev
          path: |
            extension/chrome
