name: Build dev extension from tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: "https://2cb75085e6dba41ead4774395caa4641@o4507044685938688.ingest.de.sentry.io/4507044706713680"
      SENTRY_SAMPLE_RATE: 1.0
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_VERSION_STRING: ${{github.ref_name}}-dev

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Default to prod API
        run: |
          sed -r "s/DefaultBaseUrlKey = 'Dev'/DefaultBaseUrlKey = 'Prod'/" source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts

      - name: Set Dev Sentry Settings
        run: |
          sed -r "s#\"SENTRY_DSN\": \"\",#\"SENTRY_DSN\": \"${SENTRY_DSN}\",#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json
          sed -r "s#\"SENTRY_SAMPLE_RATE\": 0.0,#\"SENTRY_SAMPLE_RATE\": ${SENTRY_SAMPLE_RATE},#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json

      - id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build Dev artifacts
        run: |
          npm run build:chrome-with-sourcemaps

      - name: Remove key in manifest
        run: |
          sed -i '/"key":/d' extension/chrome/manifest.json

      - name: Remove *.map files
        run: rm -rf extension/chrome/js/*.map

      - name: Store Chrome Dev artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-dev
          path: |
            extension/chrome
