name: Build extension

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install yarn
        run: |
          npm install --global yarn

      - id: cache-yarn
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.lock') }}

      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Enable development mode
        run: |
           sed 's/export const DEV_ENV = .*$/export const DEV_ENV = true;/' source/shared/constants.ts > constants.ts
           mv constants.ts source/shared/constants.ts

      - name: Build artifacts
        run: |
          yarn run build

      - name: Store Chrome artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chrome
          path: |
            extension/chrome

      - name: Store Firefox artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firefox
          path: |
            extension/firefox.xpi

      - name: Limit content scripts to "https://main-bvxea6i-qh3uq7skrqxzg.de-2.platformsh.site/form"
        run: |
           sed ':a;N;$!ba;s_http://\*/\*_TODELETE_2' source/manifest.json > manifest.json
           sed -i '/TODELETE/d' manifest.json
           sed ':a;N;$!ba;s_https://\*/\*_https://main-bvxea6i-qh3uq7skrqxzg.de-2.platformsh.site/form_2' manifest.json > source/manifest.json
           rm manifest.json

      - name: Disable development mode
        run: |
           sed 's/export const DEV_ENV = true;/export const DEV_ENV = false;/' source/shared/constants.ts > constants.ts
           mv constants.ts source/shared/constants.ts

      - name: Enable ID generation
        run: |
           sed 's/let disableID:boolean = true;/let disableID:boolean = false;/' source/Background/index.ts > index.ts
           mv index.ts source/Background/index.ts

      - name: Build artifacts
        run: |
          yarn run build:chrome

      - name: Store Chrome artifacts
        uses: actions/upload-artifact@v2
        with:
          name: witty-works-inclusifier
          path: |
            extension/chrome
