name: Build prod extension and source code from tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: "https://2cb75085e6dba41ead4774395caa4641@o4507044685938688.ingest.de.sentry.io/4507044706713680"
      SENTRY_SAMPLE_RATE: 0.001
      SENTRY_TRACE_RATE: 0.001
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_VERSION_STRING: ${{github.ref_name}}-prod

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Disable development mode, hide dev/local URLs, default to prod API
        run: |
          sed 's/export const DEV_ENV = true;/export const DEV_ENV = false;/' source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts
          sed -r 's/https:\/\/.+\.site\//https:\/\/127.0.0.1\//' source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts
          sed -r "s/DefaultBaseUrlKey = 'Dev'/DefaultBaseUrlKey = 'Prod'/" source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts

      - name: Set Prod Sentry Settings
        run: |
          sed -r "s#\"SENTRY_DSN\": \"\",#\"SENTRY_DSN\": \"${SENTRY_DSN}\",#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json
          sed -r "s#\"SENTRY_SAMPLE_RATE\": 0.0,#\"SENTRY_SAMPLE_RATE\": ${SENTRY_SAMPLE_RATE},#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json
          sed -r "s#\"SENTRY_TRACE_RATE\": 0.0,#\"SENTRY_TRACE_RATE\": ${SENTRY_TRACE_RATE},#" source/witty.config.json > witty.config.json
          mv witty.config.json source/witty.config.json

      - name: Remove git
        run: rm -rf .git

      - name: Zip source code
        run: zip release.zip ./ -r

      - name: Upload source code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: release.zip

      - id: cache-npm
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build Prod Firefox artifacts
        run: |
          npm run build:firefox-with-sourcemaps

      - name: Remove *.map files
        run: rm -rf extension/firefox/js/*.map

      - name: Store Firefox Prod artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: |
            extension/firefox

      - name: Remove Firefox background worker hack
        run: |
          sed -i '/"scripts": \["js\/background.bundle\.js"\],/d' source/manifest.json

      - name: Build Prod Chrome artifacts
        run: |
          npm run build:chrome-with-sourcemaps

      - name: Remove *.map files
        run: rm -rf extension/chrome/js/*.map

      - name: Remove key in manifest
        run: |
          sed -i '/"key":/d' extension/chrome/manifest.json

      - name: Store Chrome Prod artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: |
            extension/chrome
