name: Run Tests

on:
  push:
  schedule:
    # every 4 hours
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci

      - name: Enable testing mode
        run: |
          sed 's/export const TESTING = false;/export const TESTING = true;/' source/shared/constants.ts > constants.ts
          mv constants.ts source/shared/constants.ts

      - name: Build artifacts
        run: npm run build:chrome

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          PREMIUM_TEST_USER_EMAIL: ${{ secrets.PREMIUM_TEST_USER_EMAIL }}
          PREMIUM_TEST_USER_PASSWORD: ${{ secrets.PREMIUM_TEST_USER_PASSWORD }}
          HTACCESS_USERNAME: ${{ secrets.HTACCESS_USERNAME }}
          HTACCESS_PASSWORD: ${{ secrets.HTACCESS_PASSWORD }}
        run: xvfb-run npm test

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
