name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: |
          npm install --global yarn

      - id: cache-yarn
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: |
          yarn install
          
     - name: Build artifacts
        run: |
          yarn run build:chrome

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: xvfb-run npx playwright test

      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: playwright-report
      #     path: playwright-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
